### ISSUE TITLE
It doesnt work at all

### ISSUE THREAD

**Issue by Project-Onslaught** [DanieltheDeveloper/azerothcore-transmog-3.3.5a#18]
When i want to change the appearance for a item, its changing only  the icon of the item, but not the equipped item appearance

**Comment by Project-Onslaught** [comment]
UPDATE: I found the issue. It doesnt work on old created characters, its working only on new created characters. Is there a fix for this?

**Comment by Marotheit** [comment]
Interesting! I would imagine it's because the module is not creating SQL entries for characters that already exist. Let me look into this.

**Comment by Marotheit** [comment]
Thanks for reporting this issue! I have addressed this in the [#17](https://github.com/DanieltheDeveloper/azerothcore-transmog-3.3.5a/pull/17) branch if you would like to test it out.

That branch also contains a client-side AddOn fix, but this specific issue has been fixed with a server-side change to the Eluna script. Simply update the Eluna script and run the /reload eluna command in the server console.

**Comment by DCxLegend** [comment]
I tested out the updated script and AddOn fix that you have submitted and still have the same issue as above. The icons on the character menu change and even the character select screen is updated with the transmog but the model in-game does not change when applying transmogs.

**Comment by Marotheit** [comment]
How interesting! Everything seems to be working great on my end.

Just to be sure, you both also have the [AIO](https://github.com/Rochet2/AIO) client-side AddOn installed as well? When I remove the AIO AddOn from my installation, the character selection screen still shows transmogrified appearances (because the module/server sends this information before AddOns are ever loaded) but my appearance appears as unmodified in-game.

**Comment by DCxLegend** [comment]
Sorry, long weekend so I wasn't able to message right away. 
Yes, I have the AIO client-side AddOn installed and enabled and still have the issue. 
I do have the [transmog module](https://github.com/azerothcore/mod-transmog) installed but disabled (not sure if that is affecting it or not)

**Comment by DCxLegend** [comment]
Wait, it seems to be working all of a sudden after restarting the server. (I had done that several times before with no luck). Not sure exactly what fixed it?
